# Generated by Django 2.2.2 on 2019-09-23 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='teamId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profile_request', to='accounts.Teams'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_request', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectreport',
            name='pid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projectreport_request', to='accounts.Projects'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='teamid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects_request', to='accounts.Teams'),
        ),
        migrations.AlterField(
            model_name='userreport',
            name='empid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userreport_request', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userreport',
            name='projectid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userreport_request', to='accounts.Projects'),
        ),
        migrations.AlterField(
            model_name='userreport',
            name='teamid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userreport_request', to='accounts.Teams'),
        ),
    ]
