# Generated by Django 2.2.2 on 2019-09-22 19:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('desc', models.TextField(max_length=500)),
                ('deadline', models.DateField(default=datetime.date.today, verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamName', models.CharField(max_length=200)),
                ('time', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('teamLeader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('description', models.TextField(max_length=500)),
                ('contribution', models.TextField(max_length=500)),
                ('approach', models.TextField(max_length=500)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('empid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('projectid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='headSupervisor.Projects')),
                ('teamid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='headSupervisor.Teams')),
            ],
        ),
        migrations.AddField(
            model_name='projects',
            name='teamid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='headSupervisor.Teams'),
        ),
        migrations.CreateModel(
            name='ProjectReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('cumulativeRating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='headSupervisor.Projects')),
                ('teamid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='headSupervisor.Teams')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('type', models.TextField(max_length=500)),
                ('position', models.CharField(choices=[('Employee', 'Employee'), ('Supervisor', 'Supervisor'), ('Team Head', 'Team Head'), ('Head Supervisor', 'Head Supervisor')], default='Employee', max_length=20)),
                ('teamId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='headSupervisor.Teams')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
