# Generated by Django 2.2.2 on 2019-09-22 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('headSupervisor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectreport',
            name='pid',
        ),
        migrations.RemoveField(
            model_name='projectreport',
            name='teamid',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='teamid',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='teamLeader',
        ),
        migrations.RemoveField(
            model_name='userreport',
            name='empid',
        ),
        migrations.RemoveField(
            model_name='userreport',
            name='projectid',
        ),
        migrations.RemoveField(
            model_name='userreport',
            name='teamid',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='ProjectReport',
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
        migrations.DeleteModel(
            name='Teams',
        ),
        migrations.DeleteModel(
            name='UserReport',
        ),
    ]
